import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import { 
    buildQuestionnairePdfPath, 
    buildEvidencePath, 
    buildGeneralEvidencePath 
} from "@/lib/export/path-builder";

const styles = StyleSheet.create({
    page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#333' },
    header: { marginBottom: 30, borderBottom: '1px solid #ddd', paddingBottom: 15 },
    title: { fontSize: 24, fontWeight: 'bold', marginBottom: 5, color: '#111' },
    subtitle: { fontSize: 12, color: '#666' },
    section: { marginBottom: 20 },
    sectionTitle: { fontSize: 14, fontWeight: 'bold', marginBottom: 10, backgroundColor: '#f5f5f5', padding: 5 },
    row: { flexDirection: 'row', marginBottom: 5 },
    label: { width: 150, fontWeight: 'bold', color: '#555' },
    value: { flex: 1 },
    tocItem: { marginBottom: 4, paddingLeft: 10, fontFamily: 'Helvetica' },
    tocFolder: { marginBottom: 4, fontWeight: 'bold', marginTop: 8 },
});

export interface ManifestPDFProps {
    exportId: string;
    generatedAt: string;
    generatedBy: string;
    exportFormatVersion: string;
    applicationVersion: string;
    engagementName: string;
    questionnaires: { id: string; name: string }[];
    documents: { 
        id: string; 
        name: string; 
        questionnaireName?: string; 
        questionRef?: string;
    }[];
}

export const ManifestPDF = ({ 
    exportId, 
    generatedAt, 
    generatedBy, 
    exportFormatVersion, 
    applicationVersion, 
    engagementName, 
    questionnaires, 
    documents 
}: ManifestPDFProps) => {

    const generalDocs = documents.filter(d => !d.questionnaireName);
    const evidenceByQuestionnaire = documents.reduce((acc, doc) => {
        if (doc.questionnaireName) {
            if (!acc[doc.questionnaireName]) acc[doc.questionnaireName] = [];
            acc[doc.questionnaireName].push(doc);
        }
        return acc;
    }, {} as Record<string, typeof documents>);

    return (
        <Document>
            <Page size="A4" style={styles.page}>
                {/* Header */}
                <View style={styles.header}>
                    <Text style={styles.title}>CoParity Output Pack</Text>
                    <Text style={styles.subtitle}>Index & Manifest</Text>
                </View>

                {/* Engagement Metadata */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Engagement Details</Text>
                    <View style={styles.row}>
                        <Text style={styles.label}>Engagement Name:</Text>
                        <Text style={styles.value}>{engagementName}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Questionnaires Included:</Text>
                        <Text style={styles.value}>{questionnaires.length}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Evidence Files Included:</Text>
                        <Text style={styles.value}>{documents.length}</Text>
                    </View>
                </View>

                {/* System Metadata */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>System Metadata</Text>
                    <View style={styles.row}>
                        <Text style={styles.label}>Export ID:</Text>
                        <Text style={styles.value}>{exportId}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Generated At:</Text>
                        <Text style={styles.value}>{generatedAt}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Generated By:</Text>
                        <Text style={styles.value}>{generatedBy}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Format Version:</Text>
                        <Text style={styles.value}>{exportFormatVersion}</Text>
                    </View>
                    <View style={styles.row}>
                        <Text style={styles.label}>Application Version:</Text>
                        <Text style={styles.value}>{applicationVersion}</Text>
                    </View>
                </View>

                {/* Table of Contents */}
                <View style={styles.section}>
                    <Text style={styles.sectionTitle}>Table of Contents (Expected Structure)</Text>
                    
                    <Text style={styles.tocItem}>📄 README.txt</Text>
                    <Text style={styles.tocItem}>📄 Manifest.pdf</Text>
                    <Text style={styles.tocItem}>📄 _metadata/export-manifest.json</Text>

                    {questionnaires.length > 0 && (
                        <View>
                            <Text style={styles.tocFolder}>📁 Questionnaires/</Text>
                            {questionnaires.map((q, i) => (
                                <Text key={i} style={styles.tocItem}>
                                    📄 {buildQuestionnairePdfPath(q.name).replace('Questionnaires/', '')}
                                </Text>
                            ))}
                        </View>
                    )}

                    {Object.keys(evidenceByQuestionnaire).length > 0 && (
                        <View>
                            <Text style={styles.tocFolder}>📁 Evidence/</Text>
                            {Object.entries(evidenceByQuestionnaire).map(([qName, docs], i) => (
                                <View key={i}>
                                    <Text style={{...styles.tocItem, fontWeight: 'bold'}}>- 📁 {qName}/</Text>
                                    {docs.map((d, j) => {
                                        const fullPath = buildEvidencePath(qName, d.questionRef || 'Gen', d.name);
                                        const fileName = fullPath.split('/').pop();
                                        return <Text key={j} style={{...styles.tocItem, paddingLeft: 20}}>📄 {fileName}</Text>;
                                    })}
                                </View>
                            ))}
                        </View>
                    )}

                    {generalDocs.length > 0 && (
                        <View>
                            <Text style={styles.tocFolder}>📁 Evidence/General/</Text>
                            {generalDocs.map((d, i) => {
                                const fullPath = buildGeneralEvidencePath(d.name);
                                const fileName = fullPath.split('/').pop();
                                return <Text key={i} style={styles.tocItem}>📄 {fileName}</Text>;
                            })}
                        </View>
                    )}
                </View>

            </Page>
        </Document>
    );
};
