import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

// --- PDF Styles ---
const styles = StyleSheet.create({
    page: { padding: 30, fontSize: 10, fontFamily: 'Helvetica' },
    title: { fontSize: 18, marginBottom: 10, textAlign: 'center' },
    subtitle: { fontSize: 12, marginBottom: 20, textAlign: 'center', color: '#666' },
    questionBlock: { marginBottom: 15, paddingBottom: 10, borderBottom: '1px solid #eee' },
    status: { fontSize: 8, color: '#999', marginBottom: 2 },
    question: { fontSize: 12, fontWeight: 'bold', marginBottom: 5 },
    answer: { fontSize: 10, marginBottom: 5, color: '#333' },
    commentHeader: { fontSize: 9, fontStyle: 'italic', marginTop: 5, color: '#666' },
    comment: { fontSize: 9, color: '#666', marginLeft: 10 },
    metadataBlock: { marginBottom: 20, paddingBottom: 10, borderBottom: '1px solid #ddd' },
    metaRow: { flexDirection: 'row', marginBottom: 3 },
    metaLabel: { width: 100, fontSize: 8, fontWeight: 'bold', color: '#555' },
    metaValue: { flex: 1, fontSize: 8, color: '#333' },
    evidenceBlock: { marginTop: 5, padding: 5, backgroundColor: '#f9f9f9', borderLeft: '2px solid #ccc' },
    evidenceLabel: { fontSize: 8, fontStyle: 'italic', color: '#555', marginBottom: 2 },
    evidencePath: { fontSize: 8, color: '#0066cc' }
});

export interface QuestionnairePDFProps {
    title: string;
    exportMetadata?: {
        exportId: string;
        generatedAt: string;
        generatedBy: string;
        engagementName: string;
        exportFormatVersion: string;
        applicationVersion: string;
    };
    data: {
        id: string;
        status: string;
        question: string;
        answer: string;
        sourceLabel?: string;
        sourceTimestamp?: string;
        notes?: string;
        evidencePaths?: string[];
    }[];
}

// --- PDF Component ---
export const QuestionnairePDF = ({ data, title, exportMetadata }: QuestionnairePDFProps) => (
    <Document>
        <Page size="A4" style={styles.page}>
            <Text style={styles.title}>{title}</Text>
            <Text style={styles.subtitle}>Questionnaire Export</Text>

            {exportMetadata && (
                <View style={styles.metadataBlock}>
                    <View style={styles.metaRow}><Text style={styles.metaLabel}>Engagement:</Text><Text style={styles.metaValue}>{exportMetadata.engagementName}</Text></View>
                    <View style={styles.metaRow}><Text style={styles.metaLabel}>Export ID:</Text><Text style={styles.metaValue}>{exportMetadata.exportId}</Text></View>
                    <View style={styles.metaRow}><Text style={styles.metaLabel}>Generated At:</Text><Text style={styles.metaValue}>{exportMetadata.generatedAt}</Text></View>
                    <View style={styles.metaRow}><Text style={styles.metaLabel}>Generated By:</Text><Text style={styles.metaValue}>{exportMetadata.generatedBy}</Text></View>
                    <View style={styles.metaRow}><Text style={styles.metaLabel}>Format Version:</Text><Text style={styles.metaValue}>{exportMetadata.exportFormatVersion}</Text></View>
                    <View style={styles.metaRow}><Text style={styles.metaLabel}>App Version:</Text><Text style={styles.metaValue}>{exportMetadata.applicationVersion}</Text></View>
                </View>
            )}

            {data.map((item: any, i: any) => (
                <View key={i} style={styles.questionBlock}>
                    <Text style={styles.status}>Status: {item.status}</Text>
                    <Text style={styles.question}>Q{i + 1}: {item.question}</Text>
                    <Text style={styles.answer}>Answer: {item.answer || "(No Answer)"}</Text>
                    {item.sourceLabel && <Text style={styles.status}>Source: {item.sourceLabel}</Text>}
                    {item.sourceTimestamp && <Text style={styles.status}>Sourced At: {new Date(item.sourceTimestamp).toLocaleString('en-GB', { day: '2-digit', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit'})}</Text>}
                    
                    {item.evidencePaths && item.evidencePaths.length > 0 && (
                        <View style={styles.evidenceBlock}>
                            <Text style={styles.evidenceLabel}>Evidence Attached:</Text>
                            {item.evidencePaths.map((path: string, j: number) => (
                                <Text key={j} style={styles.evidencePath}>📄 {path}</Text>
                            ))}
                        </View>
                    )}

                    {item.notes && item.notes.length > 0 && (
                        <View>
                            <Text style={styles.commentHeader}>Notes:</Text>
                            {item.notes.split('\n').map((note: string, j: number) => (
                                <Text key={j} style={styles.comment}>• {note}</Text>
                            ))}
                        </View>
                    )}
                </View>
            ))}
        </Page>
    </Document>
);
