/**
 * FieldDefinitions.ts
 * 
 * Canonical mapping of Master Schema Field Numbers (1-119, excluding 94) to Prisma models.
 * This is the single source of truth for Field No → Schema mapping.
 * 
 * Naming: Uses Prisma model names (PascalCase) and field names (camelCase)
 * Database table/column names included as reference only
 */

export type FieldDefinition = {
    fieldNo: number;
    fieldName: string;
    model: string; // Legacy: Prisma model name
    field: string | null; // Legacy: Prisma field name
    appDataType: 'TEXT' | 'NUMBER' | 'DATE' | 'DATETIME' | 'PERSON_REF' | 'ORG_REF' | 'DOCUMENT_REF' | 'JSONB';
    dataType: 'string' | 'integer' | 'boolean' | 'date' | 'datetime' | 'jsonb' | 'document'; // Legacy
    isMultiValue: boolean; // New multiplicity flag
    isRepeating: boolean; // Legacy multiplicity flag
    dbTable?: string;
    dbColumn?: string;
    notes?: string;
    options?: string[];
};

export const FIELD_DEFINITIONS: Record<number, FieldDefinition> = {
    // Identity Profile (Fields 1-3, 6-10, 11-15, 26-27)
    1: {
        fieldNo: 1,
        fieldName: 'LEI validation date',
        model: 'IdentityProfile',
        field: 'leiValidationDate',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'leiValidationDate',
    },
    2: {
        fieldNo: 2,
        fieldName: 'LEI',
        model: 'IdentityProfile',
        field: 'leiCode',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'leiCode',
    },
    3: {
        fieldNo: 3,
        fieldName: 'Legal name',
        model: 'IdentityProfile',
        field: 'legalName',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'legalName',
    },

    // Entity Names (Fields 4-5) - Repeating
    4: {
        fieldNo: 4,
        fieldName: 'Trading name',
        model: 'EntityName',
        field: 'name',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: true,
        isRepeating: true,
        dbTable: 'entity_names',
        dbColumn: 'name',
    },
    5: {
        fieldNo: 5,
        fieldName: 'Previous name',
        model: 'EntityName',
        field: 'name',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: true,
        isRepeating: true,
        dbTable: 'entity_names',
        dbColumn: 'name',
        notes: 'Differentiated by type field',
    },

    // Identity Profile - Registered Address (Fields 6-10)
    6: {
        fieldNo: 6,
        fieldName: 'Registered address line 1',
        model: 'IdentityProfile',
        field: 'regAddressLine1',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'regAddressLine1',
    },
    7: {
        fieldNo: 7,
        fieldName: 'Registered address city',
        model: 'IdentityProfile',
        field: 'regAddressCity',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'regAddressCity',
    },
    8: {
        fieldNo: 8,
        fieldName: 'Registered address region',
        model: 'IdentityProfile',
        field: 'regAddressRegion',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'regAddressRegion',
    },
    9: {
        fieldNo: 9,
        fieldName: 'Registered address country',
        model: 'IdentityProfile',
        field: 'regAddressCountry',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'regAddressCountry',
    },
    10: {
        fieldNo: 10,
        fieldName: 'Registered address postcode',
        model: 'IdentityProfile',
        field: 'regAddressPostcode',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'regAddressPostcode',
    },

    // Identity Profile - HQ Address (Fields 11-15)
    11: {
        fieldNo: 11,
        fieldName: 'Headquarters address line 1',
        model: 'IdentityProfile',
        field: 'hqAddressLine1',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'hqAddressLine1',
    },
    12: {
        fieldNo: 12,
        fieldName: 'Headquarters address city',
        model: 'IdentityProfile',
        field: 'hqAddressCity',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'hqAddressCity',
    },
    13: {
        fieldNo: 13,
        fieldName: 'Headquarters address region',
        model: 'IdentityProfile',
        field: 'hqAddressRegion',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'hqAddressRegion',
    },
    14: {
        fieldNo: 14,
        fieldName: 'Headquarters address country',
        model: 'IdentityProfile',
        field: 'hqAddressCountry',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'hqAddressCountry',
    },
    15: {
        fieldNo: 15,
        fieldName: 'Headquarters address postcode',
        model: 'IdentityProfile',
        field: 'hqAddressPostcode',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'hqAddressPostcode',
    },

    // Constitutional Profile (Fields 16-18)
    16: {
        fieldNo: 16,
        fieldName: 'Registration authority GLEIF ID',
        model: 'ConstitutionalProfile',
        field: 'registrationAuthorityGleifId',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'constitutional_profiles',
        dbColumn: 'registrationAuthorityGleifId',
    },
    17: {
        fieldNo: 17,
        fieldName: 'Registration authority',
        model: 'ConstitutionalProfile',
        field: 'registrationAuthority',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'constitutional_profiles',
        dbColumn: 'registrationAuthority',
    },
    18: {
        fieldNo: 18,
        fieldName: 'Registered number',
        model: 'ConstitutionalProfile',
        field: 'registeredNumber',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'constitutional_profiles',
        dbColumn: 'registeredNumber',
    },

    // Entity Info Profile (Fields 19-25)
    19: {
        fieldNo: 19,
        fieldName: 'GLEIF entity category',
        model: 'EntityInfoProfile',
        field: 'gleifEntityCategory',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'entity_info_profiles',
        dbColumn: 'gleifEntityCategory',
    },
    20: {
        fieldNo: 20,
        fieldName: 'Industry classification',
        model: 'IndustryClassification',
        field: 'code',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: true,
        isRepeating: true,
        dbTable: 'industry_classifications',
        dbColumn: 'code',
    },
    21: {
        fieldNo: 21,
        fieldName: 'Entity legal form code',
        model: 'EntityInfoProfile',
        field: 'entityLegalFormCode',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'entity_info_profiles',
        dbColumn: 'entityLegalFormCode',
    },
    22: {
        fieldNo: 22,
        fieldName: 'Country of formation',
        model: 'EntityInfoProfile',
        field: 'countryOfFormation',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'entity_info_profiles',
        dbColumn: 'countryOfFormation',
    },
    23: {
        fieldNo: 23,
        fieldName: 'Country code',
        model: 'EntityInfoProfile',
        field: 'countryCode',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'entity_info_profiles',
        dbColumn: 'countryCode',
    },
    24: {
        fieldNo: 24,
        fieldName: 'Entity legal form local name',
        model: 'EntityInfoProfile',
        field: 'entityLegalFormLocalName',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'entity_info_profiles',
        dbColumn: 'entityLegalFormLocalName',
    },
    25: {
        fieldNo: 25,
        fieldName: 'Entity legal form transliterated name',
        model: 'EntityInfoProfile',
        field: 'entityLegalFormTransliteratedName',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'entity_info_profiles',
        dbColumn: 'entityLegalFormTransliteratedName',
    },

    // Identity Profile - Entity Status (Fields 26-27)
    26: {
        fieldNo: 26,
        fieldName: 'Entity status',
        model: 'IdentityProfile',
        field: 'entityStatus',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'entityStatus',
    },
    27: {
        fieldNo: 27,
        fieldName: 'Entity creation date',
        model: 'IdentityProfile',
        field: 'entityCreationDate',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'identity_profiles',
        dbColumn: 'entityCreationDate',
    },

    // LEI Registration (Fields 28-35)
    28: {
        fieldNo: 28,
        fieldName: 'LEI registration date',
        model: 'LeiRegistration',
        field: 'leiRegistrationDate',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'lei_registrations',
        dbColumn: 'leiRegistrationDate',
    },
    29: {
        fieldNo: 29,
        fieldName: 'LEI registration update date',
        model: 'LeiRegistration',
        field: 'leiRegistrationUpdateDate',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'lei_registrations',
        dbColumn: 'leiRegistrationUpdateDate',
    },
    30: {
        fieldNo: 30,
        fieldName: 'LEI registration status',
        model: 'LeiRegistration',
        field: 'leiRegistrationStatus',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'lei_registrations',
        dbColumn: 'leiRegistrationStatus',
    },
    31: {
        fieldNo: 31,
        fieldName: 'LEI registration next renewal',
        model: 'LeiRegistration',
        field: 'leiRegistrationNextRenewal',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'lei_registrations',
        dbColumn: 'leiRegistrationNextRenewal',
    },
    32: {
        fieldNo: 32,
        fieldName: 'LEI issuer LEI',
        model: 'LeiRegistration',
        field: 'leiIssuerLei',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'lei_registrations',
        dbColumn: 'leiIssuerLei',
    },
    33: {
        fieldNo: 33,
        fieldName: 'LEI issuer',
        model: 'LeiRegistration',
        field: 'leiIssuer',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'lei_registrations',
        dbColumn: 'leiIssuer',
    },
    34: {
        fieldNo: 34,
        fieldName: 'LEI corroboration level',
        model: 'LeiRegistration',
        field: 'leiCorroborationLevel',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'lei_registrations',
        dbColumn: 'leiCorroborationLevel',
    },
    35: {
        fieldNo: 35,
        fieldName: 'LEI corroboration source',
        model: 'LeiRegistration',
        field: 'leiCorroborationSource',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'lei_registrations',
        dbColumn: 'leiCorroborationSource',
    },

    // Relationship Profile - Direct Parent (Fields 36-39)
    36: {
        fieldNo: 36,
        fieldName: 'Direct parent ID',
        model: 'RelationshipProfile',
        field: 'directParentId',
        appDataType: 'ORG_REF',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'directParentId',
    },
    37: {
        fieldNo: 37,
        fieldName: 'Direct parent',
        model: 'RelationshipProfile',
        field: 'directParent',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'directParent',
    },
    38: {
        fieldNo: 38,
        fieldName: 'Direct parent ID type',
        model: 'RelationshipProfile',
        field: 'directParentIdType',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'directParentIdType',
    },
    39: {
        fieldNo: 39,
        fieldName: 'Direct parent relationship',
        model: 'RelationshipProfile',
        field: 'directParentRelationship',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'directParentRelationship',
    },

    // Relationship Profile - Ultimate Parent (Fields 40-43)
    40: {
        fieldNo: 40,
        fieldName: 'Ultimate parent ID',
        model: 'RelationshipProfile',
        field: 'ultimateParentId',
        appDataType: 'ORG_REF',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'ultimateParentId',
    },
    41: {
        fieldNo: 41,
        fieldName: 'Ultimate parent',
        model: 'RelationshipProfile',
        field: 'ultimateParent',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'ultimateParent',
    },
    42: {
        fieldNo: 42,
        fieldName: 'Ultimate parent ID type',
        model: 'RelationshipProfile',
        field: 'ultimateParentIdType',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'ultimateParentIdType',
    },
    43: {
        fieldNo: 43,
        fieldName: 'Ultimate parent relationship',
        model: 'RelationshipProfile',
        field: 'ultimateParentRelationship',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'ultimateParentRelationship',
    },

    // Relationship Profile - Fund Manager (Fields 44-48)
    44: {
        fieldNo: 44,
        fieldName: 'Fund manager ID',
        model: 'RelationshipProfile',
        field: 'fundManagerId',
        appDataType: 'ORG_REF',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'fundManagerId',
    },
    45: {
        fieldNo: 45,
        fieldName: 'Fund manager',
        model: 'RelationshipProfile',
        field: 'fundManager',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'fundManager',
    },
    46: {
        fieldNo: 46,
        fieldName: 'Fund manager ID type',
        model: 'RelationshipProfile',
        field: 'fundManagerIdType',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'fundManagerIdType',
    },
    47: {
        fieldNo: 47,
        fieldName: 'Fund manager relationship',
        model: 'RelationshipProfile',
        field: 'fundManagerRelationship',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'fundManagerRelationship',
    },
    48: {
        fieldNo: 48,
        fieldName: 'Fund manager relationship status',
        model: 'RelationshipProfile',
        field: 'fundManagerRelationshipStatus',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'fundManagerRelationshipStatus',
    },

    // Relationship Profile - Umbrella Fund (Fields 49-53)
    49: {
        fieldNo: 49,
        fieldName: 'Umbrella fund ID',
        model: 'RelationshipProfile',
        field: 'umbrellaFundId',
        appDataType: 'ORG_REF',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'umbrellaFundId',
    },
    50: {
        fieldNo: 50,
        fieldName: 'Umbrella fund',
        model: 'RelationshipProfile',
        field: 'umbrellaFund',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'umbrellaFund',
    },
    51: {
        fieldNo: 51,
        fieldName: 'Umbrella fund ID type',
        model: 'RelationshipProfile',
        field: 'umbrellaFundIdType',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'umbrellaFundIdType',
    },
    52: {
        fieldNo: 52,
        fieldName: 'Umbrella fund relationship',
        model: 'RelationshipProfile',
        field: 'umbrellaFundRelationship',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'umbrellaFundRelationship',
    },
    53: {
        fieldNo: 53,
        fieldName: 'Umbrella fund relationship status',
        model: 'RelationshipProfile',
        field: 'umbrellaFundRelationshipStatus',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'umbrellaFundRelationshipStatus',
    },

    // Relationship Profile - Exceptions (Fields 54-55)
    54: {
        fieldNo: 54,
        fieldName: 'LEI direct parent exception',
        model: 'RelationshipProfile',
        field: 'leiDirectParentException',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'leiDirectParentException',
    },
    55: {
        fieldNo: 55,
        fieldName: 'LEI ultimate parent exception',
        model: 'RelationshipProfile',
        field: 'leiUltimateParentException',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'leiUltimateParentException',
    },

    // Document-only field (Field 56)
    56: {
        fieldNo: 56,
        fieldName: 'Constitutional and formation documents',
        model: 'DocumentRegistry',
        field: null,
        appDataType: 'DOCUMENT_REF',
        dataType: 'document',
        isMultiValue: true,
        isRepeating: false,
        notes: 'Document upload only',
    },

    // Constitutional Profile (Fields 57-59)
    57: {
        fieldNo: 57,
        fieldName: 'Registration authority GLEIF ID (duplicate)',
        model: 'ConstitutionalProfile',
        field: 'registrationAuthorityGleifId',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'constitutional_profiles',
        dbColumn: 'registrationAuthorityGleifId',
        notes: 'Same as Field 16',
    },
    58: {
        fieldNo: 58,
        fieldName: 'Registration authority (duplicate)',
        model: 'ConstitutionalProfile',
        field: 'registrationAuthority',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'constitutional_profiles',
        dbColumn: 'registrationAuthority',
        notes: 'Same as Field 17',
    },
    59: {
        fieldNo: 59,
        fieldName: 'Registered number (duplicate)',
        model: 'ConstitutionalProfile',
        field: 'registeredNumber',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'constitutional_profiles',
        dbColumn: 'registeredNumber',
        notes: 'Same as Field 18',
    },

    // Document-only fields (Fields 60-61)
    60: {
        fieldNo: 60,
        fieldName: 'Certificate of incorporation',
        model: 'DocumentRegistry',
        field: null,
        appDataType: 'DOCUMENT_REF',
        dataType: 'document',
        isMultiValue: true,
        isRepeating: false,
        notes: 'Document upload only',
    },
    61: {
        fieldNo: 61,
        fieldName: 'Memorandum and articles of association',
        model: 'DocumentRegistry',
        field: null,
        appDataType: 'DOCUMENT_REF',
        dataType: 'document',
        isMultiValue: true,
        isRepeating: false,
        notes: 'Document upload only',
    },

    // Stakeholders (Fields 62-73)
    62: {
        fieldNo: 62,
        fieldName: 'List of ultimate beneficial owners',
        model: 'Stakeholder',
        field: 'role',
        appDataType: 'PERSON_REF',
        dataType: 'string',
        isMultiValue: true,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'role',
        notes: 'Role = UBO. Can also point to Org.',
        options: ['DIRECTOR', 'UBO', 'CONTROLLER'],
    },
    63: {
        fieldNo: 63,
        fieldName: 'List of company directors',
        model: 'Stakeholder',
        field: 'role',
        appDataType: 'PERSON_REF',
        dataType: 'string',
        isMultiValue: true,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'role',
        notes: 'Role = DIRECTOR. Can also point to Org.',
        options: ['DIRECTOR', 'UBO', 'CONTROLLER'],
    },
    64: {
        fieldNo: 64,
        fieldName: 'List of persons controlling',
        model: 'Stakeholder',
        field: 'role',
        appDataType: 'PERSON_REF',
        dataType: 'string',
        isMultiValue: true,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'role',
        notes: 'Role = CONTROLLER. Can also point to Org.',
        options: ['DIRECTOR', 'UBO', 'CONTROLLER'],
    },
    65: {
        fieldNo: 65,
        fieldName: 'Full name (individual)',
        model: 'Stakeholder',
        field: 'fullName',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'fullName',
    },
    66: {
        fieldNo: 66,
        fieldName: 'Date and place of birth',
        model: 'Stakeholder',
        field: 'dateOfBirth',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'dateOfBirth',
    },
    67: {
        fieldNo: 67,
        fieldName: 'Nationalities',
        model: 'Stakeholder',
        field: 'nationalities',
        appDataType: 'JSONB',
        dataType: 'jsonb',
        isMultiValue: true,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'nationalities',
    },
    68: {
        fieldNo: 68,
        fieldName: 'ID including proof of address',
        model: 'Stakeholder',
        field: 'idDocumentId',
        appDataType: 'DOCUMENT_REF',
        dataType: 'string',
        isMultiValue: true,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'idDocumentId',
        notes: 'FK to DocumentRegistry',
    },
    69: {
        fieldNo: 69,
        fieldName: 'Company legal name (corporate)',
        model: 'Stakeholder',
        field: 'legalName',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'legalName',
    },
    70: {
        fieldNo: 70,
        fieldName: 'LEI (corporate)',
        model: 'Stakeholder',
        field: 'leiCode',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'leiCode',
    },
    71: {
        fieldNo: 71,
        fieldName: 'Registration authority GLEIF ID (corporate)',
        model: 'Stakeholder',
        field: 'registrationAuthorityGleifId',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'registrationAuthorityGleifId',
    },
    72: {
        fieldNo: 72,
        fieldName: 'Registration authority (corporate)',
        model: 'Stakeholder',
        field: 'registrationAuthority',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'registrationAuthority',
    },
    73: {
        fieldNo: 73,
        fieldName: 'Registered number (corporate)',
        model: 'Stakeholder',
        field: 'registeredNumber',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'stakeholders',
        dbColumn: 'registeredNumber',
    },

    // Document-only field (Field 74)
    74: {
        fieldNo: 74,
        fieldName: 'Ownership structure chart',
        model: 'DocumentRegistry',
        field: null,
        appDataType: 'DOCUMENT_REF',
        dataType: 'document',
        isMultiValue: true,
        isRepeating: false,
        notes: 'Document upload only',
    },

    // Compliance Profile (Fields 75-80)
    75: {
        fieldNo: 75,
        fieldName: 'Group structure (names and relationship)',
        model: 'RelationshipProfile',
        field: 'groupStructureJson',
        appDataType: 'JSONB',
        dataType: 'jsonb',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'relationship_profiles',
        dbColumn: 'groupStructureJson',
    },
    76: {
        fieldNo: 76,
        fieldName: 'Regulation',
        model: 'RegulatoryProfile',
        field: 'regulationJson',
        appDataType: 'JSONB',
        dataType: 'jsonb',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'regulatory_profiles',
        dbColumn: 'regulationJson',
    },
    77: {
        fieldNo: 77,
        fieldName: 'High risk sectors',
        model: 'ComplianceProfile',
        field: 'highRiskSectors',
        appDataType: 'JSONB',
        dataType: 'jsonb',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'compliance_profiles',
        dbColumn: 'highRiskSectors',
    },
    78: {
        fieldNo: 78,
        fieldName: 'Primary business activity',
        model: 'EntityInfoProfile',
        field: 'primaryBusinessActivity',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'entity_info_profiles',
        dbColumn: 'primaryBusinessActivity',
    },
    79: {
        fieldNo: 79,
        fieldName: 'Secondary business activity',
        model: 'EntityInfoProfile',
        field: 'secondaryBusinessActivity',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'entity_info_profiles',
        dbColumn: 'secondaryBusinessActivity',
    },
    80: {
        fieldNo: 80,
        fieldName: 'Description of principal activities',
        model: 'EntityInfoProfile',
        field: 'principalActivitiesDesc',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'entity_info_profiles',
        dbColumn: 'principalActivitiesDesc',
    },

    // Tax Registrations (Field 81)
    81: {
        fieldNo: 81,
        fieldName: 'Tax ID by country',
        model: 'TaxRegistration',
        field: 'taxId',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: true,
        isRepeating: true,
        dbTable: 'tax_registrations',
        dbColumn: 'taxId',
    },

    // Document-only fields (Fields 82, 84)
    82: {
        fieldNo: 82,
        fieldName: 'Recent financial report',
        model: 'DocumentRegistry',
        field: null,
        appDataType: 'DOCUMENT_REF',
        dataType: 'document',
        isMultiValue: true,
        isRepeating: false,
        notes: 'Document upload only',
    },
    83: {
        fieldNo: 83,
        fieldName: 'Website address',
        model: 'EntityInfoProfile',
        field: 'website',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'entity_info_profiles',
        dbColumn: 'website',
    },
    84: {
        fieldNo: 84,
        fieldName: 'Prospectus',
        model: 'DocumentRegistry',
        field: null,
        appDataType: 'DOCUMENT_REF',
        dataType: 'document',
        isMultiValue: true,
        isRepeating: false,
        notes: 'Document upload only',
    },

    // Financial Profile (Fields 85-90)
    85: {
        fieldNo: 85,
        fieldName: 'Last AML/KYC review date',
        model: 'KycProfile',
        field: 'lastReviewDate',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'kyc_profiles',
        dbColumn: 'lastReviewDate',
    },
    86: {
        fieldNo: 86,
        fieldName: 'Next AML/KYC review date',
        model: 'KycProfile',
        field: 'nextReviewDate',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'kyc_profiles',
        dbColumn: 'nextReviewDate',
    },
    87: {
        fieldNo: 87,
        fieldName: 'Last site visit date',
        model: 'KycProfile',
        field: 'lastSiteVisitDate',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'kyc_profiles',
        dbColumn: 'lastSiteVisitDate',
    },
    88: {
        fieldNo: 88,
        fieldName: 'Last screening date',
        model: 'KycProfile',
        field: 'lastScreeningDate',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'kyc_profiles',
        dbColumn: 'lastScreeningDate',
    },
    89: {
        fieldNo: 89,
        fieldName: 'Last adverse news screening date',
        model: 'KycProfile',
        field: 'lastAdverseNewsDate',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'kyc_profiles',
        dbColumn: 'lastAdverseNewsDate',
    },
    90: {
        fieldNo: 90,
        fieldName: 'Last transaction monitoring review date',
        model: 'KycProfile',
        field: 'lastTxmReviewDate',
        appDataType: 'DATETIME',
        dataType: 'datetime',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'kyc_profiles',
        dbColumn: 'lastTxmReviewDate',
    },

    // Derivatives Profile (Fields 91-93)
    91: {
        fieldNo: 91,
        fieldName: 'ISDA master regulatory disclosure letter',
        model: 'DerivativesProfile',
        field: 'isdaMasterRegulatoryDisclosureLetterRef',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'derivatives_profiles',
        dbColumn: 'isdaMasterRegulatoryDisclosureLetterRef',
        notes: 'Document reference',
    },
    92: {
        fieldNo: 92,
        fieldName: 'ISDA EMIR classification letter',
        model: 'DerivativesProfile',
        field: 'isdaEmirClassificationLetterRef',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'derivatives_profiles',
        dbColumn: 'isdaEmirClassificationLetterRef',
        notes: 'Document reference',
    },
    93: {
        fieldNo: 93,
        fieldName: 'ISDA US self-disclosure letter',
        model: 'DerivativesProfile',
        field: 'isdaUsSelfdisclosureLetterRef',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'derivatives_profiles',
        dbColumn: 'isdaUsSelfdisclosureLetterRef',
        notes: 'Document reference',
    },

    // Field 94 is a placeholder (excluded)

    // Document-only field (Field 95)
    95: {
        fieldNo: 95,
        fieldName: 'List of authorised traders',
        model: 'DocumentRegistry',
        field: null,
        appDataType: 'DOCUMENT_REF',
        dataType: 'document',
        isMultiValue: true,
        isRepeating: false,
        notes: 'Document upload only - data also in AuthorizedTrader table',
    },

    // Authorized Traders (Fields 96-101)
    96: {
        fieldNo: 96,
        fieldName: 'Trader full name',
        model: 'AuthorizedTrader',
        field: 'fullName',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'authorized_traders',
        dbColumn: 'fullName',
    },
    97: {
        fieldNo: 97,
        fieldName: 'Trader email',
        model: 'AuthorizedTrader',
        field: 'email',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'authorized_traders',
        dbColumn: 'email',
    },
    98: {
        fieldNo: 98,
        fieldName: 'Trader telephone',
        model: 'AuthorizedTrader',
        field: 'phone',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'authorized_traders',
        dbColumn: 'phone',
    },
    99: {
        fieldNo: 99,
        fieldName: 'Trader mobile',
        model: 'AuthorizedTrader',
        field: 'mobile',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'authorized_traders',
        dbColumn: 'mobile',
    },
    100: {
        fieldNo: 100,
        fieldName: 'Proof of trading authority',
        model: 'AuthorizedTrader',
        field: 'authorityDocumentId',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'authorized_traders',
        dbColumn: 'authorityDocumentId',
        notes: 'Can be document OR attestation text',
    },
    101: {
        fieldNo: 101,
        fieldName: 'Products authorized',
        model: 'AuthorizedTrader',
        field: 'products',
        appDataType: 'JSONB',
        dataType: 'jsonb',
        isMultiValue: true,
        isRepeating: true,
        dbTable: 'authorized_traders',
        dbColumn: 'products',
    },

    // Trading Profile (Fields 102-103)
    102: {
        fieldNo: 102,
        fieldName: 'Board minute authorising individuals to trade',
        model: 'TradingProfile',
        field: 'boardMinuteAuthorisingIndividualsRef',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'trading_profiles',
        dbColumn: 'boardMinuteAuthorisingIndividualsRef',
        notes: 'Document reference',
    },
    103: {
        fieldNo: 103,
        fieldName: 'Board minute authorising entry into transactions',
        model: 'TradingProfile',
        field: 'boardMinuteAuthorisingTransactionsRef',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'trading_profiles',
        dbColumn: 'boardMinuteAuthorisingTransactionsRef',
        notes: 'Document reference',
    },

    // Contacts (Fields 104-106)
    104: {
        fieldNo: 104,
        fieldName: 'Contact address',
        model: 'Contact',
        field: 'address',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'contacts',
        dbColumn: 'address',
    },
    105: {
        fieldNo: 105,
        fieldName: 'Contact attention',
        model: 'Contact',
        field: 'attention',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'contacts',
        dbColumn: 'attention',
    },
    106: {
        fieldNo: 106,
        fieldName: 'Contact email',
        model: 'Contact',
        field: 'email',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'contacts',
        dbColumn: 'email',
    },

    // Contact Profile (Fields 107-109)
    107: {
        fieldNo: 107,
        fieldName: 'Process agent',
        model: 'ContactProfile',
        field: 'processAgent',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'contact_profiles',
        dbColumn: 'processAgent',
    },
    108: {
        fieldNo: 108,
        fieldName: 'Office',
        model: 'ContactProfile',
        field: 'office',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'contact_profiles',
        dbColumn: 'office',
    },
    109: {
        fieldNo: 109,
        fieldName: 'Is multibranch party',
        model: 'ContactProfile',
        field: 'isMultibranchParty',
        appDataType: 'TEXT',
        dataType: 'boolean',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'contact_profiles',
        dbColumn: 'isMultibranchParty',
    },

    // Derivatives Profile (Fields 110-112)
    110: {
        fieldNo: 110,
        fieldName: 'ISDA reporting delegation agreement',
        model: 'DerivativesProfile',
        field: 'isdaReportingDelegationAgreementRef',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'derivatives_profiles',
        dbColumn: 'isdaReportingDelegationAgreementRef',
        notes: 'Document reference',
    },
    111: {
        fieldNo: 111,
        fieldName: 'ISDA FIA EMIR reporting delegation',
        model: 'DerivativesProfile',
        field: 'isdaFiaEmirReportingDelegationRef',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'derivatives_profiles',
        dbColumn: 'isdaFiaEmirReportingDelegationRef',
        notes: 'Document reference',
    },
    112: {
        fieldNo: 112,
        fieldName: 'ISDA 2013 reporting protocol side letter',
        model: 'DerivativesProfile',
        field: 'isda2013ReportingProtocolSideLetterRef',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'derivatives_profiles',
        dbColumn: 'isda2013ReportingProtocolSideLetterRef',
        notes: 'Document reference',
    },

    // Contact Profile (Fields 113-115)
    113: {
        fieldNo: 113,
        fieldName: 'Portfolio data email',
        model: 'ContactProfile',
        field: 'portfolioDataEmail',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'contact_profiles',
        dbColumn: 'portfolioDataEmail',
    },
    114: {
        fieldNo: 114,
        fieldName: 'Discrepancy notice email',
        model: 'ContactProfile',
        field: 'discrepancyNoticeEmail',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'contact_profiles',
        dbColumn: 'discrepancyNoticeEmail',
    },
    115: {
        fieldNo: 115,
        fieldName: 'Dispute notice email',
        model: 'ContactProfile',
        field: 'disputeNoticeEmail',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: false,
        dbTable: 'contact_profiles',
        dbColumn: 'disputeNoticeEmail',
    },

    // Settlement Instructions (Fields 116-119)
    116: {
        fieldNo: 116,
        fieldName: 'Settlement currency',
        model: 'SettlementInstruction',
        field: 'currency',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'settlement_instructions',
        dbColumn: 'currency',
    },
    117: {
        fieldNo: 117,
        fieldName: 'Settlement account name',
        model: 'SettlementInstruction',
        field: 'accountName',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'settlement_instructions',
        dbColumn: 'accountName',
    },
    118: {
        fieldNo: 118,
        fieldName: 'Settlement account number',
        model: 'SettlementInstruction',
        field: 'accountNumber',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'settlement_instructions',
        dbColumn: 'accountNumber',
    },
    119: {
        fieldNo: 119,
        fieldName: 'Settlement IBAN/SWIFT',
        model: 'SettlementInstruction',
        field: 'ibanSwift',
        appDataType: 'TEXT',
        dataType: 'string',
        isMultiValue: false,
        isRepeating: true,
        dbTable: 'settlement_instructions',
        dbColumn: 'ibanSwift',
    },
};

/**
 * Get field definition by Field No
 * @throws Error if Field No is unknown
 */
export function getFieldDefinition(fieldNo: number): FieldDefinition {
    const def = FIELD_DEFINITIONS[fieldNo];
    if (!def) {
        throw new Error(`Unknown Field No: ${fieldNo}`);
    }
    return def;
}

/**
 * Get all field definitions for a specific Prisma model
 */
export function getFieldsByModel(modelName: string): FieldDefinition[] {
    return Object.values(FIELD_DEFINITIONS).filter((def: any) => def.model === modelName);
}

/**
 * Check if a Field No is document-only (no data column)
 */
export function isDocumentOnlyField(fieldNo: number): boolean {
    const def = FIELD_DEFINITIONS[fieldNo];
    return def ? def.field === null : false;
}

/**
 * Get all Field Nos mapped to a specific model
 */
export function getFieldNosByModel(modelName: string): number[] {
    return Object.values(FIELD_DEFINITIONS)
        .filter((def: any) => def.model === modelName && def.field !== null)
        .map((def: any) => def.fieldNo);
}

/**
 * Validate Field No exists in canonical range
 */
export function isValidFieldNo(fieldNo: number): boolean {
    return fieldNo in FIELD_DEFINITIONS;
}
