import { NextRequest, NextResponse } from "next/server";
// @ts-ignore: types are outdated for archiver v7 ESM
import { ZipArchive } from "archiver";
import { PassThrough } from "stream";
import { getIdentity } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { v4 as uuidv4 } from "uuid";
import { buildOutputPackFilename } from "@/lib/export/path-builder";

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const { engagementId, questionnaireIds = [], documentIds = [] } = body;

        if (!engagementId) {
            return NextResponse.json({ error: "Missing engagementId" }, { status: 400 });
        }

        const identity = await getIdentity();
        const user = identity?.userId ? await prisma.user.findUnique({ where: { id: identity.userId } }) : null;

        const engagement = await prisma.fIEngagement.findUnique({
            where: { id: engagementId },
            include: { org: true }
        });

        if (!engagement) {
            return NextResponse.json({ error: "Engagement not found" }, { status: 404 });
        }

        const exportId = uuidv4();
        const generatedAt = new Date().toISOString();
        const engagementName = engagement.org.name;
        
        const exportFormatVersion = "1.0.0";
        const applicationVersion = "0.1.0"; // from package.json conceptually

        // Set up archiver and stream
        const passThrough = new PassThrough();
        const archive = new ZipArchive({ zlib: { level: 9 } });
        
        archive.on("error", (err: any) => {
            console.error("Archiver Error:", err);
            throw err;
        });

        archive.pipe(passThrough);

        // --- Phase 1: Scaffold Files ---

        // 1. export-manifest.json
        const manifest = {
            exportId,
            exportFormatVersion,
            applicationVersion,
            engagementId,
            engagementName,
            generatedAt,
            generatedBy: {
                userId: identity?.userId || "unknown",
                name: user?.name || "Unknown User",
                email: user?.email || "unknown@example.com"
            },
            questionnaires: questionnaireIds.map((id: string) => ({ id })),
            documents: documentIds.map((id: string) => ({ id, checksums: { sha256: null } }))
        };

        archive.append(JSON.stringify(manifest, null, 2), { name: "_metadata/export-manifest.json" });

        // 2. README.txt
        const readmeContent = `OUTPUT PACK FOR: ${engagementName}
=========================================
Export ID: ${exportId}
Generated At: ${generatedAt}
Generated By: ${user?.name || user?.email || "Unknown User"}

Format Version: ${exportFormatVersion}
Application Version: ${applicationVersion}

NOTE: This is a Phase 1 static export scaffold. 
PDF generation and native evidence hydration are not yet implemented in this export.
`;
        archive.append(readmeContent, { name: "README.txt" });

        // Finalize archive
        archive.finalize();

        const filename = buildOutputPackFilename(engagementName, new Date(generatedAt));

        // @ts-ignore: Next.js supports taking Node's ReadableStream natively via Response in App Router if returned as any or casted appropriately
        return new NextResponse(passThrough as any, {
            headers: {
                "Content-Type": "application/zip",
                "Content-Disposition": `attachment; filename="${filename}"`
            }
        });

    } catch (error: any) {
        console.error("Output Pack ZIP Error:", error);
        return NextResponse.json({ error: error.message || "Failed to generate Output Pack" }, { status: 500 });
    }
}
