import { NextRequest, NextResponse } from "next/server";
// @ts-ignore: types are outdated for archiver v7 ESM
import { ZipArchive } from "archiver";
import { PassThrough } from "stream";
import { getIdentity } from "@/lib/auth";
import prisma from "@/lib/prisma";
import { v4 as uuidv4 } from "uuid";
import React from "react";
import { renderToStream } from "@react-pdf/renderer";
import { buildQuestionnairePdfPath, buildEvidencePath, buildOutputPackFilename, buildGeneralEvidencePath } from "@/lib/export/path-builder";
import { ManifestPDF } from "@/components/pdf/manifest-pdf";
import { QuestionnairePDF } from "@/components/pdf/questionnaire-pdf";

export async function POST(req: NextRequest) {
    try {
        const body = await req.json();
        const { engagementId, questionnaireIds = [], documentIds = [] } = body;

        if (!engagementId) {
            return NextResponse.json({ error: "Missing engagementId" }, { status: 400 });
        }

        const identity = await getIdentity();
        const user = identity?.userId ? await prisma.user.findUnique({ where: { id: identity.userId } }) : null;

        const engagement = await prisma.fIEngagement.findUnique({
            where: { id: engagementId },
            include: { org: true }
        });

        if (!engagement) {
            return NextResponse.json({ error: "Engagement not found" }, { status: 404 });
        }

        const exportId = uuidv4();
        const generatedAt = new Date().toISOString();
        const engagementName = engagement.org.name;
        
        const exportFormatVersion = "1.0.0";
        const applicationVersion = "0.1.0"; // from package.json conceptually

        // Set up archiver and stream
        const passThrough = new PassThrough();
        const archive = new ZipArchive({ zlib: { level: 9 } });
        
        archive.on("error", (err: any) => {
            console.error("Archiver Error:", err);
            throw err;
        });

        archive.pipe(passThrough);

        // --- Prepare Metadata & Data ---
        const dbQuestionnaires = await prisma.questionnaire.findMany({
            where: { id: { in: questionnaireIds } },
            select: { id: true, name: true }
        });

        const dbDocuments = await prisma.document.findMany({
            where: { id: { in: documentIds } },
            include: {
                question: {
                    include: { questionnaire: true }
                }
            }
        });

        const documentsForManifest = dbDocuments.map((d: any) => {
            const qName = d.question?.questionnaire?.name;
            const qRef = d.question ? (d.question.compactText || d.question.text.substring(0, 15) + "...") : undefined;
            const generatedPath = qName 
                ? buildEvidencePath(qName, qRef || 'Gen', d.name)
                : buildGeneralEvidencePath(d.name);
            
            return {
                id: d.id,
                name: d.name,
                questionnaireName: qName,
                questionRef: qRef,
                generatedPath,
                fileUrl: d.fileUrl
            };
        });

        // 1. export-manifest.json
        const manifest = {
            exportId,
            exportFormatVersion,
            applicationVersion,
            engagementId,
            engagementName,
            generatedAt,
            generatedBy: {
                userId: identity?.userId || "unknown",
                name: user?.name || "Unknown User",
                email: user?.email || "unknown@example.com"
            },
            questionnaires: questionnaireIds.map((id: string) => ({ id })),
            documents: documentsForManifest.map((d: any) => ({ 
                id: d.id, 
                path: d.generatedPath,
                checksums: { sha256: null } 
            }))
        };

        archive.append(JSON.stringify(manifest, null, 2), { name: "_metadata/export-manifest.json" });

        // 2. README.txt
        const readmeContent = `OUTPUT PACK FOR: ${engagementName}
=========================================
Export ID: ${exportId}
Generated At: ${generatedAt}
Generated By: ${user?.name || user?.email || "Unknown User"}

Format Version: ${exportFormatVersion}
Application Version: ${applicationVersion}

NOTE: This export pack includes Questionnaire PDFs and Original Native Evidence.
`;
        archive.append(readmeContent, { name: "README.txt" });

        // 3. Manifest.pdf
        const manifestElement = React.createElement(ManifestPDF, {
            exportId,
            generatedAt,
            generatedBy: user?.name || user?.email || "Unknown User",
            exportFormatVersion,
            applicationVersion,
            engagementName,
            questionnaires: dbQuestionnaires,
            documents: documentsForManifest
        });

        const manifestStream = await renderToStream(manifestElement as any);
        archive.append(manifestStream as any, { name: "Manifest.pdf" });

        // 4. Questionnaire PDFs (Sequential)
        for (const q of dbQuestionnaires) {
            const questions = await prisma.question.findMany({
                where: { questionnaireId: q.id },
                orderBy: { order: 'asc' },
                include: {
                    comments: { include: { user: true }, orderBy: { createdAt: 'asc' } },
                    documents: { where: { id: { in: documentIds }, isDeleted: false } }
                }
            });

            const exportData = questions.map((question: any) => {
                let resolvedAnswer = question.answer || "";
                if (typeof resolvedAnswer === 'object' && resolvedAnswer !== null) {
                    resolvedAnswer = JSON.stringify(resolvedAnswer);
                } else {
                    resolvedAnswer = String(resolvedAnswer ?? "");
                }

                const evidencePaths = question.documents.map((doc: any) => {
                    return buildEvidencePath(q.name, question.compactText || question.text.substring(0, 15) + "...", doc.name);
                });

                return {
                    id: question.id,
                    status: question.status,
                    question: question.text,
                    answer: resolvedAnswer,
                    notes: question.comments.map((c: any) => `[${c.user?.name || 'User'}]: ${c.text}`).join("\n"),
                    evidencePaths
                };
            });

            const qPdfElement = React.createElement(QuestionnairePDF, {
                title: q.name,
                exportMetadata: {
                    exportId,
                    generatedAt,
                    generatedBy: user?.name || user?.email || "Unknown User",
                    engagementName,
                    exportFormatVersion,
                    applicationVersion
                },
                data: exportData
            });

            const qPdfStream = await renderToStream(qPdfElement as any);
            const qPdfPath = buildQuestionnairePdfPath(q.name);
            archive.append(qPdfStream as any, { name: qPdfPath });
        }

        // 5. Native Evidence Hydration
        const BATCH_SIZE = 5;
        for (let i = 0; i < documentsForManifest.length; i += BATCH_SIZE) {
            const batch = documentsForManifest.slice(i, i + BATCH_SIZE);
            await Promise.all(batch.map(async (doc: any) => {
                try {
                    if (!doc.fileUrl) {
                        throw new Error("Missing fileUrl");
                    }
                    const res = await fetch(doc.fileUrl);
                    if (!res.ok) {
                        throw new Error(`Failed to fetch: ${res.statusText}`);
                    }
                    const buffer = Buffer.from(await res.arrayBuffer());
                    archive.append(buffer, { name: doc.generatedPath });
                } catch (error: any) {
                    console.error(`Failed to download document ${doc.id}:`, error);
                    const pathParts = doc.generatedPath.split('/');
                    const filename = pathParts.pop();
                    const dirPath = pathParts.join('/');
                    const errorPath = `${dirPath}/_ERROR_DOWNLOADING_${filename}.txt`;
                    archive.append(
                        `Error downloading file from URL: ${doc.fileUrl}\nReason: ${error.message}\n`,
                        { name: errorPath }
                    );
                }
            }));
        }

        // Finalize archive
        archive.finalize();

        const filename = buildOutputPackFilename(engagementName, new Date(generatedAt));

        // @ts-ignore: Next.js supports taking Node's ReadableStream natively via Response in App Router if returned as any or casted appropriately
        return new NextResponse(passThrough as any, {
            headers: {
                "Content-Type": "application/zip",
                "Content-Disposition": `attachment; filename="${filename}"`
            }
        });

    } catch (error: any) {
        console.error("Output Pack ZIP Error:", error);
        return NextResponse.json({ error: error.message || "Failed to generate Output Pack" }, { status: 500 });
    }
}
