
export interface SchemaCategory {
    id: string;
    title: string;
    description: string;
    fields: string[];
}

export const MASTER_SCHEMA_CATEGORIES: SchemaCategory[] = [
    {
        id: "1",
        title: "1. Entity Identity & Legal Existence",
        description: "What the entity is",
        fields: [
            "Full legal name",
            "Registered / legal address",
            "Tax address and mailing address",
            "Country of incorporation",
            "Legal form (Ltd, GmbH, SCSp, LP, Trust, etc.)",
            "Company / trade register numbers",
            "Articles of Association, Memorandum, constitutional documents"
        ]
    },
    {
        id: "2",
        title: "2. Ownership & Control Structure (UBO)",
        description: "Who ultimately owns or controls the entity",
        fields: [
            "Direct and indirect shareholders",
            "Ownership percentages (≥10%, ≥25%)",
            "Voting rights",
            "Ultimate Beneficial Owners (UBOs)",
            "Factual / effective control",
            "Trust, fund, SPV or layered ownership structures",
            "Confirmation of no additional beneficial owners"
        ]
    },
    {
        id: "3",
        title: "3. Directors, Management & Key Principals",
        description: "Who runs the entity",
        fields: [
            "Directors and controlling directors",
            "CEO, CFO, Chair and senior management",
            "Country of residence",
            "Date of birth",
            "Identification documents"
        ]
    },
    {
        id: "4",
        title: "4. Authorised Representatives & Mandates",
        description: "Who can act on behalf of the entity",
        fields: [
            "KYC representative(s)",
            "Authorised signatories",
            "Bank mandates",
            "Certificates of incumbency",
            "Authority to open accounts or enter into transactions"
        ]
    },
    {
        id: "5",
        title: "5. Business Activities & Purpose",
        description: "What the entity does",
        fields: [
            "Nature of business",
            "Sector / industry",
            "Purpose of the banking or financial relationship",
            "Intended use of products or services",
            "Acting as principal or agent"
        ]
    },
    {
        id: "6",
        title: "6. Geographic Footprint & Operating Countries",
        description: "Where the entity operates (non-sanctions)",
        fields: [
            "Countries of operation",
            "Branches, subsidiaries and permanent establishments",
            "Assets held by country",
            "Revenue generated by country",
            "Purchases or sourcing by country"
        ]
    },
    {
        id: "7",
        title: "7. Sanctions & Restricted Jurisdictions Exposure",
        description: "Links to comprehensively sanctioned countries",
        fields: [
            "Direct or indirect presence in sanctioned jurisdictions",
            "Assets, revenues or purchases linked to sanctioned countries",
            "Counterparties linked to sanctioned governments or entities",
            "Payment routing involving sanctioned jurisdictions",
            "Licensing requirements (OFAC, EU, UN, etc.)"
        ]
    },
    {
        id: "8",
        title: "8. Ultra-High-Risk / High-Risk Country Nexus",
        description: "Elevated jurisdictional risk",
        fields: [
            "Involvement in ultra-high-risk or high-risk countries",
            "Percentage of revenue linked to such countries",
            "Expected changes in exposure",
            "Currencies used in related transactions",
            "Goods or services involved"
        ]
    },
    {
        id: "9",
        title: "9. Goods, Services & Trade Controls",
        description: "Cross-border flows",
        fields: [
            "Import and export activities",
            "Transport, transhipment or logistics",
            "Dual-use goods or technologies",
            "Origin and destination of goods and services",
            "Trade or export control licences"
        ]
    },
    {
        id: "10",
        title: "10. Financial Crime & AML Risk",
        description: "Money-laundering and illicit finance exposure",
        fields: [
            "AML confirmations or letters",
            "Source of funds and source of wealth",
            "Use of intermediaries or agents",
            "Screening and monitoring processes",
            "Adverse media or negative information"
        ]
    },
    {
        id: "11",
        title: "11. Anti-Corruption & Bribery",
        description: "Corruption risk and controls",
        fields: [
            "Involvement in high-risk sectors",
            "Operations in low CPI countries",
            "Anti-bribery and corruption policies",
            "Internal controls and governance",
            "Audit or assessment of anti-corruption measures"
        ]
    },
    {
        id: "12",
        title: "12. Tax Residency & Tax Reporting",
        description: "Tax status and obligations",
        fields: [
            "Tax residence",
            "FATCA classification",
            "CRS classification",
            "W-8 / W-9 forms",
            "Automatic Exchange of Information (AEOI) confirmations"
        ]
    },
    {
        id: "13",
        title: "13. Regulatory Classification (Client Status)",
        description: "How the entity is classified under regulation",
        fields: [
            "Professional / retail client status",
            "EMIR classification (FC, NFC-, NFC+, SFC)",
            "Dodd-Frank applicability",
            "Canadian derivatives reporting scope",
            "MiFID client categorisation"
        ]
    },
    {
        id: "14",
        title: "14. Trading, Hedging & Derivatives Activity",
        description: "Use of financial instruments",
        fields: [
            "Use of derivatives",
            "Purpose of derivatives (hedging vs trading)",
            "Acting as principal or agent in trades",
            "Margin and collateral requirements",
            "Reporting delegation for derivatives"
        ]
    },
    {
        id: "15",
        title: "15. Reporting, Disclosure & Consents",
        description: "Operational acknowledgements",
        fields: [
            "Consent to off-venue trading",
            "Delegation of regulatory reporting",
            "Data sharing and disclosure consents",
            "Opt-in / opt-out declarations"
        ]
    },
    {
        id: "16",
        title: "16. Internal Controls & Compliance Framework",
        description: "How compliance is managed",
        fields: [
            "Existence of compliance or legal function",
            "Sanctions and screening controls",
            "Export control or trade compliance programmes",
            "Frequency of audits or reviews",
            "Governance and oversight arrangements"
        ]
    },
    {
        id: "17",
        title: "17. Documentation & Evidence",
        description: "Supporting proof",
        fields: [
            "Identification documents",
            "Licences and permits",
            "Policies and procedures",
            "Registers, certificates and extracts",
            "Evidence supporting questionnaire responses"
        ]
    }
];
